analytics:
  ua: ''
  gtag: ''
  gtm: ''
  ga_prod: ''
breadcrumbs:
  goal:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  indicator:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  post:
    - path: /
      label: general.home
    - path: /news
      label: menu.updates
cookie_consent_form:
  enabled: false
country:
  name: Peterborough
  adjective: Canadian
create_goals:
  previous_next_links: false
  goal_content_heading: ''
#  goals: []
  goals:
    - goal: 11
      heading: Make cities and human settlements inclusive, safe, resilient and sustainable, keeping in mind our region's exceptional attributes, diversity, culture, heritage, unique composition of rural, urban, and an abundance of natural landscapes.
      content:  >-
        ### **Inclusive:** Inclusive communities are where community members feel safe, respected, and comfortable in being themselves and expressing all aspects of their identities. It is a place where each person shares a sense of belonging with its other members.

        ### **Safe:** Safe communities are where all community members have the ability, regardless of Human Rights-protected grounds such as gender, race, age, income, sexuality, language or ability, to participate fully and freely in the local society.

        ### **Resilient:** Resilient communities have the ability to prepare for, absorb, recover from, and adapt to stresses and adverse events.
        
        ### **Sustainable:** Sustainable communities meet the needs of the present without compromising the environmental, social, and economic aspects of the past, present and future generations, and have strong social and physical infrastructures. The decisions we make today should result in a sustainable world and sustainable relationships for many generations into the future.

create_indicators:
  previous_next_links: false
create_pages:
  - filename: ''
    folder: /goals
    layout: goals
    title: general.goals
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: status.reporting_status
  - filename: ''
    folder: /search
    layout: search
    title: search.search
custom_css: []
custom_js:
  - /assets/js/custom.js
data_edit_url: data
data_fields:
  units: ''
  series: ''
date_formats: []
disclaimer:
  phase: ''
  message: ''
  hidden: true
email_contacts:
  questions: info@sustainablepeterborough.ca
  suggestions: info@sustainablepeterborough.ca
  functional: info@sustainablepeterborough.ca
empty_metadata_placeholder: ''
empty_metadata_placeholder_sources: ''
environment: staging
footer_language_toggle: none
footer_menu:
#  - path: /contact-us
#    translation_key: menu.contact_us
#  - path: 'https://twitter.com/sustainableptbo'
#    translation_key: general.twitter
#  - path: 'https://facebook.com/sustainablepeterborough'
#    translation_key: general.facebook
  - path: /about/cookies-and-privacy/
    translation_key: menu.cookies
frontpage_cards:
#  - title: frontpage.download_all
#    content: ''
#    include: components/download-all-data.html
#    button_label: ''
#    button_link: ''
#    rule_color: ''
#  - title: Lorem ipsum
#    content: |
#      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi mollis
#      cursus est sed dapibus.
#    include: ''
#    button_label: Read more
#    button_link: 'https://example.com'
#    rule_color: ''
#  - title: Nam vestibulum
#    content: |
#      Nam vestibulum, purus quis porttitor imperdiet, nisl sem mollis nisl, a
#      interdum risus enim vitae tortor. Donec feugiat accumsan rutrum.
#    include: ''
#    button_label: Read more
#    button_link: 'https://example.com'
#    rule_color: ''
frontpage_goals_grid:
#  title: frontpage.heading_short
#  description: frontpage.instructions_shorter
  title: >-
    <p>Welcome to the Greater Peterborough Area's Indicator Framework Data Dashboard</p>
  description: >-
    <p>This framework was established for tracking and advancing local progress towards the Sustainable Development Goals. Select each goal to view available data for the global and localized indicators. The Greater Peterborough Area encompasses the City of Peterborough, Peterborough County (upper tier municipality representing the Townships of Asphodel-Norwood, Cavan Monaghan, Douro-Dummer, Havelock-Belmont-Methuen, North Kawartha, Otonabee-South Monaghan, Selwyn, and the Municipality of Trent Lakes), Curve Lake and Hiawatha First Nations. While we aim to source and capture inclusive data across the entire region, sometimes data is unavailable or incomplete and is identified as such where published. This data platform is constantly evolving and developing so check back often. To submit data, please <a href="mailto:info@sustainablepeterborough.ca">email us</a></p>
frontpage_introduction_banner:
  title: frontpage.intro_title
#description: frontpage.intro_body
  description: >-
    <p>The <a target="_blank" href="https://www.un.org/sustainabledevelopment/sustainable-development-goals/">Sustainable Development Goals (SDGs)</a> are a universal call to action to end poverty, protect the planet and improve the lives and prospects of everyone, everywhere. The 17 Goals were adopted by all UN Member States in 2015, as part of the <a target="_blank" href="https://sdgs.un.org/2030agenda">2030 Agenda for Sustainable Development</a>. The <a target="_blank" href="https://sdgcif-data-canada-oddcic-donnee.github.io/">Canadian Indicator Framework</a> was established by Statistics Canada to support <a target="_blank" href="https://www.canada.ca/en/employment-social-development/programs/agenda-2030/moving-forward.html">Canada's implementation of the SDGs</a>. Locally, Sustainable Peterborough's (SP) mandate is centered around helping the Greater Peterborough Area community implement and track progress towards the SDGs, as identified in our <a target="_blank" href="https://sustainablepeterborough.ca/wp-content/uploads/2022/04/Sustainable-Peterborough-Strategic-Plan-Final-Apr.-2022-compressed.pdf">Strategic Plan</a>, created with stakeholder engagement and direction from the City of Peterborough and Peterborough County. SP also established this local framework to support and align with the Canadian Federal Government's SDG achievement efforts.</p>
goal_image_base: 'https://open-sdg.org/sdg-translations/assets/img/goals'
goal_image_extension: ''
goals_page:
#  title: general.goals
  title: Sustainable Development Goals
#  description: frontpage.instructions_shorter
  description: >-
    <p>This framework was established for tracking and advancing local progress towards the Sustainable Development Goals. Select each goal to view available data for the global and localized indicators. The Greater Peterborough Area encompasses the City of Peterborough, Peterborough County (upper tier municipality representing the Townships of Asphodel-Norwood, Cavan Monaghan, Douro-Dummer, Havelock-Belmont-Methuen, North Kawartha, Otonabee-South Monaghan, Selwyn, and the Municipality of Trent Lakes), Curve Lake and Hiawatha First Nations. While we aim to source and capture inclusive data across the entire region, sometimes data is unavailable or incomplete and is identified as such where published. This data platform is constantly evolving and developing so check back often. To submit data, please <a href="mailto:info@sustainablepeterborough.ca">email us</a></p>
graph_color_headline_high_contrast: '#55a6e5'
graph_color_set: accessible
graph_color_list: []
graph_color_number: 0
graph_title_from_series: false
header_language_toggle: dropdown
hide_empty_metadata: true
hide_single_series: true
hide_single_unit: true
ignored_disaggregations: []
indicator_config_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/indicator-config
  translation_link: ''
indicator_data_form:
  enabled: true
  repository_link: /tree/develop/data
indicator_metadata_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/meta
  translation_link: ''
  language: ''
  scopes:
    - national
#    - global
  exclude_fields: []
  translated: false
indicator_tabs:
  tab_1: ''
  tab_2: ''
  tab_3: ''
  tab_4: ''
languages:
  - en
#  - es
languages_public: []
logos: []
map_layers: []
map_options:
  disaggregation_controls: false
  minZoom: 5
  maxZoom: 10
  tileURL: ''
  tileOptions:
    id: ''
    accessToken: ''
    attribution: ''
  colorRange: chroma.brewer.BuGn
  noValueColor: '#f0f0f0'
  styleNormal:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#888888'
    dashArray: ''
  styleHighlighted:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#111111'
    dashArray: ''
  styleStatic:
    weight: 2
    opacity: 1
    fillOpacity: 0
    color: '#172d44'
    dashArray: '5,5'
menu:
#  - path: /
#    translation_key: general.home
#    dropdown: []
#  - path: /goals
#    translation_key: general.goals
#    dropdown: []
#  - path: /reporting-status
#    translation_key: menu.reporting_status
#    dropdown: []
#  - path: /news
#    translation_key: menu.updates
#    dropdown: []
#  - path: /faq
#    translation_key: menu.faq
#    dropdown: []
#  - path: /about
#    translation_key: menu.about
#    dropdown: []
metadata_edit_url: metadata
metadata_tabs:
  - scope: national
#    title: indicator.national_metadata
    title: 'Local Metadata'
#    description: indicator.national_metadata_blurb
#    description: 'The table below contains more information regarding the indicator. This is a proxy local indicator closest to the corresponding global SDG indicator, as supported by data availability. Please note that even when data supporting the global SDG indicator is fully available from local or Canadian statistics, this table should be consulted for additional information.'
    description: 'The table below contains more information regarding this indicator.'
#  - scope: global
#    title: indicator.global_metadata
#    description: indicator.global_metadata_blurb
#  - scope: sources
#    title: indicator.sources
#    description: ''
meta_tags: []
news:
  category_links: false
observation_attributes: []
progress_status:
  status_heading: ''
  status_help: ''
  status_types: []
progressive_web_app:
  enabled: false
  name: ''
  short_name: ''
  precaching: false
proxy_indicators:
  label: ''
  description: ''
remote_data_prefix: 'https://sustainablepeterborough-staging.github.io/data/'
reporting_status:
  title: status.reporting_status
  description: status.description
  disaggregation_indicator_count_label: ''
  disaggregation_tabs: true
  status_types:
    - value: notstarted
      #label: status.no_data_available
      label: Not Available
      hide_on_goal_pages: false
    - value: complete
      #label: status.reported_online
      label: Reported
      hide_on_goal_pages: false
    - value: inprogress
      #label: status.inprogress
      label: In Progress
      hide_on_goal_pages: false
    - value: notapplicable
      label: status.not_applicable
      hide_on_goal_pages: false
repository_url_data: 'https://github.com/SustainablePeterborough-staging/data'
repository_url_site: 'https://github.com/SustainablePeterborough-staging/site'
search_index_boost: []
search_index_extra_fields: []
site_config_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/_data
  translation_link: ''
time_series_attributes:
  - field: COMMENT_TS
    label: indicator.footnote
  - field: DATA_LAST_UPDATE
    label: metadata_fields.national_data_update_url
use_new_config_forms: true
validate_indicator_config: false
validate_site_config: false
x_axis_label: ''
#
